server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payments
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  # Configurações de gerenciamento de transações
  transaction:
    rollback-on-commit-failure: true

  rabbitmq:
    host: localhost

digidine:
  broker:
    exchange:
      paymentNotificationExchange: digidine.payment.notification
      orderNotificationExchange: digidine.order.notification
    key:
      paymentNotificationKey: ms.payment.notification
      orderNotificationKey: ms.order.notification
    queue:
      payment: digidine.payment.notification.queue
      order: digidine.order.notification.queue